# Generated by Django 6.0.3 on 2026-03-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('forward_to', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_expiry', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProxmoxVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmid', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('node', models.CharField(max_length=100)),
                ('cpu', models.FloatField(blank=True, null=True)),
                ('memory', models.BigIntegerField(blank=True, null=True)),
                ('disk', models.BigIntegerField(blank=True, null=True)),
                ('uptime', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
