# Generated by Django 6.0.3 on 2026-03-24 02:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('state', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='km01, km02, etc.', max_length=100, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=True)),
                ('proxmox_version', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitor.node')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PacketCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('duration', models.IntegerField(default=120)),
                ('summary', models.JSONField(default=dict)),
                ('pcap_path', models.CharField(blank=True, max_length=500)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.node')),
            ],
        ),
        migrations.CreateModel(
            name='SystemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('memory_bytes', models.BigIntegerField(default=0)),
                ('cpu_percent', models.FloatField(default=0)),
                ('ports', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='monitor.node')),
            ],
        ),
        migrations.DeleteModel(
            name='HostedSite',
        ),
        migrations.DeleteModel(
            name='NetworkHost',
        ),
        migrations.AddField(
            model_name='proxmoxvm',
            name='vm_type',
            field=models.CharField(choices=[('qemu', 'QEMU'), ('lxc', 'LXC')], default='lcx', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='cpu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='disk',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='memory',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='uptime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='vmid',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='networkconnection',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='monitor.node'),
        ),
        migrations.AlterField(
            model_name='proxmoxvm',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='monitor.node'),
        ),
        migrations.AlterUniqueTogether(
            name='proxmoxvm',
            unique_together={('node', 'vmid')},
        ),
        migrations.AddIndex(
            model_name='nodesnapshot',
            index=models.Index(fields=['timestamp'], name='monitor_nod_timesta_42c8de_idx'),
        ),
    ]
